### ISSUE TITLE
Readme feedback 

### ISSUE THREAD

**Issue by gundarskokts** [michaellgraves/Twitter-PyBot#1]
Minor thing to make the entire flow more self explanatory - add the following steps to the readme 

-1) Clone the repo in github / download zip 
0) Edit the config files 

Also, can use other file transfer tools such as FileZilla. 

Will do more testing but deployment steps 1-9 worked like a charm.

**Comment by michaellgraves** [comment]
cool, thanks! I updated the readme.... let me know if there is anything
else.

**Comment by michaellgraves** [comment]
updated readme. thx
